version: "3"

services:
  # NGINX Container
  nginx:
    build: ./build/nginx
    # image: srconklin/mynginx
    # Mount our shared webroot volume
    volumes:
      - ./www:/opt/sites/default
      - ./build/nginx/config:/etc/nginx

  # CFML Engine
  cfml:
    #image: ortussolutions/commandbox
    build: ./build/lucee
    # bind public port to 8080
    ports:
      - "8080:8080"
    volumes:
      - ./www:/app
    environment:
      PORT: 8080
      SSL_PORT: 8443
      cfconfigfile: /app/.cfconfig.json
      # CFCONFIG: /app/myConfig.json
      # BOX_INSTALL: "true"
      # FINALIZE_STARTUP: "false"
      # CFENGINE: lucee5
      # HEADLESS: FALSE
      # cfconfig_adminPassword: admin123

  # MySQL Server
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Pri234Sc"
      MYSQL_DATABASE: "test_db"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
      #  - ./build/mysql/initdb:/docker-entrypoint-initdb.d
volumes:
  my-datavolume:
