version: "3"

services:
  # NGINX Container
  nginx:
    #build: ./build/nginx
    image: srconklin/mynginx
    ports:
      - "80:80"
      - "443:443"
    # Mount our shared webroot volume
    volumes:
      - ./www:/opt/sites/default
      - ./build/nginx/config:/etc/nginx
      - ./build/nginx/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/drierite-sandbox.cf/fullchain.pem:/etc/letsencrypt/live/drierite-sandbox.cf/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/drierite-sandbox.cf/privkey.pem:/etc/letsencrypt/live/drierite-sandbox.cf/privkey.pem

  # CFML Engine
  cfml:
    image: ortussolutions/commandbox
    # bind public port to 8080
    ports:
      - "8080:8080"
    volumes:
      - ./www:/app
    environment:
      PORT: 8080
      SSL_PORT: 8443
      # CFCONFIG: /app/myConfig.json
      cfconfigfile: /app/myConfig.json
      CFENGINE: adobe@11
      # HEADLESS: FALSE
      #cfconfig_adminPassword: admin123

  # MySQL Server
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Pri234Sc"
      MYSQL_DATABASE: "test_db"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./build/mysql/initdb:/docker-entrypoint-initdb.d
