version: "3"

services:
  # web enngine
  nginx:
    # container_name: nginx
    build: ./build/nginx
    image: my_nginx:latest
    # bind public port to 8080
    ports:
      - "80:80"
      - "443:443"
    # Mount our shared webroot volume
    volumes:
      - ./www:/opt/sites/default
      - ./build/nginx/config:/etc/nginx
      - ./build/nginx/nginx-local.conf:/etc/nginx/conf.d/default.conf

  # CFML Engine
  cfml:
    # container_name: cfml
    image: ortussolutions/commandbox:lucee5
    # build: ./build/ortussolutions
    # image: my_cfml:latest
    # bind public port to 8080
    ports:
      - "8080:8080"
    volumes:
      - ./www:/app
    environment:
      PORT: 8080
      SSL_PORT: 8443
      cfconfigfile: /app/.cfconfig.json
      # CFCONFIG: /app/myConfig.json
      # BOX_INSTALL: "true"
      # FINALIZE_STARTUP: "false"
      # CFENGINE: adobe11
      # HEADLESS: FALSE
      # cfconfig_adminPassword: admin123
# volumes:
#   mssqlvolume:
#   mysqlvolume:
