version: "3"

services:
  # NGINX Container
  nginx:
    ports:
      - "80:80"
      - "443:443"
    # Mount our shared webroot volume
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build/nginx/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/www.thehost.com/fullchain.pem:/etc/letsencrypt/live/www.thehost.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/www.thehost.com/privkey.pem:/etc/letsencrypt/live/www.thehost.com/privkey.pem
